alias: "Auto: Ladung starten bei Überschuss"
description: Wenn genug Strom übrig ist, das Laden auf PV steht aber keine Ladung aktiv ist
trigger:
  - platform: numeric_state
    entity_id: input_number.smartwb1_current
    above: "5"
    for: "00:00:05"
    below: "17"
condition:
  - condition: state
    entity_id: input_select.smartwb1_mode
    state: Solar
  - condition: state
    entity_id: sensor.smartwb1
    state: "2"
action:
  - service: shell_command.smartwb1_setstatus
    data:
      status: "true"
  - service: shell_command.smartwb1_setcurrent
    data:
      ampere: 6
mode: single
